#!/bin/bash
#
echo -n "Sisesta oma vanus: "
read vanus
if test $vanus -gt 0 -a $vanus -lt 11
then
	echo "Te olete laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
	echo "Olete nooruk"
elif test $vanus -ge 18 -a $vanus -lt 63
then
	echo "Olete täiskasvanu"
elif test $vanus -ge 63
then 
	echo "Olete senioor"
else
	echo "Viga vanuse esitamisel"
fi
#
# skripti lõpp
