#!/bin/bash
#
# Skripti algus
echo -n "Sisesta reisijate arv: "
read reisijad
echo -n "Sisesta kohtade arv bussis: "
read kohad
#
# arvutused
# jagame reisijad kohtade arvuga 
bussid=$(($reisijad / $kohad))
# vaatame, palju on reisijaid, kes ei saanud kohta bussis - need on ylejaanud reisijad
ylejaanud=$(($reisijad % $kohad)) 
# kui on olemas ylejaanud, tuleb suurendada busside arvu 1 v6rra
if test $ylejaanud -gt 0
then
	bussid=$(($bussid + 1))
fi
# valjastan tulemused
#
echo "Kokku on vaja $bussid täisbussi"
#
# skripti lopp

