#!/bin/bash
#
# kolmnurga pindala arvutamine
#
# skript algab
#
echo
echo -n "Sisesta kylje a vaartus"
read a
echo -n "Sisesta kylje b vaartus"
read b
echo -n "Sisesta kylje c vaartus"
read c
#
# arvutamine
#
p=`echo "scale=2; ($a+$b+$c)/2" | bc`
s=`echo "scale=2;sqrt($p*($p-$a)*($p-$b)*($p-$c))" | bc`
echo "Pindala = $s"
#
# Skripti lõpp
