#!/bin/bash
#
echo "Sisesta ridade arv: "
read rida
echo "Sisesta tarnide arv reas: "
read tarn
for (( i=1; i<=5; i++ ))
do 	
	echo -n "$i "
	if [ $i -eq 1 -o $i -eq $rida ]; then
	
for ((  j = 1; j <= $tarn; j++ ))
do
	echo -n "* "
done
else
	echo -n "* "
	for ((j=2; j<$tarn; j++ ))
	do
		echo -n "  "
	done
	echo -n "* "
	fi
	echo
done
